version: "3"

services:
  alfred:
    image: alfred
    depends_on:
      - alfred-db
    ports:
      - 8080:80
    environment:
      TOKEN: TOKEN
      HOST: alfred-db
      PORT: 5432
      USER: USER
      DBNAME: DBNAME
      SSLMODE: disable
    command: ["./app"]  

  alfred-db:
    image: postgres:10-alpine
    volumes:
      - alfreddata:/var/lib/postgresql/data

volumes:
  alfreddata:
